stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: img_fiware-wilma_v7.7:${CICD_EXECUTION_SEQUENCE}
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch: {}
      event: {}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./wilma deployment.yaml
    when:
      branch: {}
      event: {}
  - applyYamlConfig:
      path: ./wilma_service.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - applyYamlConfig:
      path: ./ingress.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        sshpass -p password ssh -tt -o StrictHostKeyChecking=no newuser@192.168.100.178 ./check_pod_status.sh p-kpggk-pipeline wilma
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        apt-get update
        echo Y | apt-get install npm
        npm -v
        ls -ltr
        sleep 300
        npm install -g newman
        newman run ./Wilma.postman_collection.json
  when:
    branch: {}
    event: {}
timeout: 150
notification: {}
