stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: extras/docker/Dockerfile
      buildContext: .
      tag: wilma_img:${CICD_EXECUTION_SEQUENCE}
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  - applyYamlConfig:
      path: ./service.yaml
  - applyYamlConfig:
      path: ./ingress.yaml
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |+
        apt-get update
        echo Y | apt-get install npm
        npm -v
        npm install -g newman
        newman run http://192.168.100.178/csp_containerizationandautomation/wilma/raw/master/Wilma.postman_collection.json
  when:
    branch: {}
    event: {}

timeout: 150
notification: {}
